#config_version=5
mode:
    start_events: ball_started
    priority: 100
    
variable_player:
  s_sling_left_active:
    score: 100
  s_slingshot_right_active:
    score: 100    
  s_jet_left_active:
    score: 50
    jet_count: 1
  s_jet_right_active:
    score: 50
    jet_count: 1
  s_jet_down_active:
    score: 50
    jet_count: 1  
    
slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: 'Bumpers Count: (jet_count) Multiplicateur: (bonus_multiplier)'
        y: 40%
     