#config_version=5
##! mode: Kraken
mode:
  start_events: kraken2_go
  priority: 300
  stop_events: ball_will_end, end_kraken2_done

shots:
  sh_kraken2_1:
    hit_events: left_loop_hit
    profile: kraken_phase_2_pro
    show_tokens:      
      leds: l_left_loop 
  sh_kraken2_2:
    hit_events: left_ramp_hit
    profile: kraken_phase_2_pro
    show_tokens:
      leds: l_left_ramp
  sh_kraken2_3:
    hit_events: upper_loop_hit
    profile: kraken_phase_2_pro
    show_tokens:
      leds: l_upper_loop  
  sh_kraken2_4:
    hit_events: right_ramp_hit
    profile: kraken_phase_2_pro
    show_tokens:
      leds: l_right_ramp
  sh_kraken2_5:
    hit_events: right_loop_hit
    profile: kraken_phase_2_pro
    show_tokens:
      leds: l_right_loop

shot_profiles:  
  kraken_phase_2_pro:
    states:
      - name: lit  # step 3
        show: "purple_lit"
      - name: flash
        show: "purple_flashing_lit"
        speed: 2
      - name: redlit  # step 1
        show: "red_lit"              
    loop: true

shot_groups:
  kraken2_tentacules_group:
    shots: sh_kraken2_1, sh_kraken2_3, sh_kraken2_5
    #  ,sh_kraken_4, sh_kraken_2
    reset_events: kraken2_tentacules_group_complete

show_player:
  mode_kraken2_started:
    kraken_level_2:
      loops: 0    
  kraken2_tentacules_group_complete{state=="redlit"}:    
    kraken_rainbow:      
      loops: 0
      events_when_completed: end_kraken2_done, krakenFinal_go

