#config_version=5
##! mode: super_jets
mode:
    start_events: ball_starting
    priority: 200
    stop_events: ball_will_end

shots:
  jets:
    switch: s_jet_down, s_jet_left, s_jet_right

counters:
  lb_jets_count:
    count_events: jets_hit
    starting_count: 0
    count_complete_value: 100
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: Super_Jets_Go
    debug: true

  lb_jets_resume:
    enable_events: mode_base_started{current_player.sj_active>0}
    count_events: jets_hit
    starting_count: 0
    count_complete_value: 25
    count_interval: 1
    direction: up
    persist_state: false
    events_when_complete: Super_Jets_Resume_Go
    debug: true
    reset_on_complete: true

event_player:
  Super_Jets_Go:
    start_mode_super_jets
  Super_Jets_Resume_Go:
    start_mode_super_jets

variable_player:
  s_jet_down_active:
    score: 200
  s_jet_left_active:
    score: 200
  s_jet_right_active:
    score: 200
  mode_super_jets_started:
    sj_active:
      int: 1
      action: set

show_player:
  # mode_super_jets_setup_started{current_player.sj_active>0}:
  #   super_jets_on:
  #     show_tokens:
  #       lights: l_super_jets
  # mode_super_jets_setup_stopped:
  #   super_jets_off:
  #     show_tokens:
  #       lights: l_super_jets