#config_version=5
##! mode: super_loop
mode:
    start_events: ball_starting
    priority: 220
    stop_events: ball_will_end

counters:
  lb_loop_count:
    count_events: left_loop_hit, right_loop_hit, upper_loop_hit
    starting_count: 0
    count_complete_value: 9
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: Super_Loop_Go
    debug: true

  lb_loop_resume:
    enable_events: mode_base_started{current_player.sl_active>0}
    count_events: left_loop_hit, right_loop_hit, upper_loop_hit
    starting_count: 0
    count_complete_value: 8
    count_interval: 1
    direction: up
    persist_state: false
    events_when_complete: Super_Loop_Resume_Go
    debug: true
    reset_on_complete: true

event_player:
  Super_Loop_Go:
    start_mode_super_loop
  Super_Loop_Resume_Go:
    start_mode_super_loop

variable_player:
  right_loop_hit:
    score: 200
  left_loop_hit:
    score: 200
  upper_loop_hit:
    score: 500
  mode_super_loop_started:
    sl_active:
      int: 1
      action: set